--------------------------------------------------------
--  File created - środa-maja-29-2019   
--------------------------------------------------------
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_CUST_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_ORDER_ITEMS_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_ORD_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_PROD_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_USERS_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."HIBERNATE_SEQUENCE";
DROP TABLE "SZKOLAJAZDY"."HIBERNATE_SEQUENCES";
DROP TABLE "SZKOLAJAZDY"."INSTRUKTORZY";
DROP TABLE "SZKOLAJAZDY"."KATEGORIE";
DROP TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW";
DROP TABLE "SZKOLAJAZDY"."KURSANCI";
DROP TABLE "SZKOLAJAZDY"."PLATNOSCI";
DROP TABLE "SZKOLAJAZDY"."REZERWACJE";
DROP TABLE "SZKOLAJAZDY"."USLUGI";
DROP FUNCTION "SZKOLAJAZDY"."CUSTOM_AUTH";
DROP FUNCTION "SZKOLAJAZDY"."CUSTOM_HASH";
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table HIBERNATE_SEQUENCES
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."HIBERNATE_SEQUENCES" 
   (	"SEQUENCE_NAME" VARCHAR2(255 CHAR), 
	"NEXT_VAL" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSTRUKTORZY
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."INSTRUKTORZY" 
   (	"INSTRUKTOR_ID" NUMBER(19,0), 
	"CZY_ADMIN" NUMBER(19,0), 
	"DATA_DODANIA" DATE, 
	"EMAIL" VARCHAR2(20 CHAR), 
	"GODZ_ROZPOCZECIA" VARCHAR2(20 CHAR), 
	"GODZ_ZAKONCZENIA" VARCHAR2(20 CHAR), 
	"HASLO" VARCHAR2(20 CHAR), 
	"IMIE" VARCHAR2(20 CHAR), 
	"NAZWISKO" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KATEGORIE
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."KATEGORIE" 
   (	"KATEGORIA_ID" NUMBER(19,0), 
	"SYMBOL" VARCHAR2(5 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KATEGORIE_INSTRUKTOROW
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" 
   (	"ID_WPISU" NUMBER(19,0), 
	"INSTRUCTOR_ID" NUMBER(19,0), 
	"KATEGORIA_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KURSANCI
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."KURSANCI" 
   (	"KURSANT_ID" NUMBER(19,0), 
	"DATA_REJESTRACJI" DATE, 
	"EMAIL" VARCHAR2(20 CHAR), 
	"HASLO" VARCHAR2(20 CHAR), 
	"IMIE" VARCHAR2(20 CHAR), 
	"NAZWISKO" VARCHAR2(20 CHAR), 
	"PESEL" VARCHAR2(20 CHAR), 
	"PKK" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLATNOSCI
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."PLATNOSCI" 
   (	"PLATNOSC_ID" NUMBER(19,0), 
	"DATA_PLATNOSCI" DATE, 
	"KURSANT_ID" NUMBER(19,0), 
	"KWOTA" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."REZERWACJE" 
   (	"REZERWACJA_ID" NUMBER(19,0), 
	"DATA_DODANIA" DATE, 
	"DATA_REZERWACJI" DATE, 
	"GODZ_ROZPOCZECIA" VARCHAR2(20 CHAR), 
	"INSTRUKTOR_ID" NUMBER(19,0), 
	"KATEGORIA_ID" NUMBER(19,0), 
	"KURSANT_ID" NUMBER(19,0), 
	"USLUGA_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USLUGI
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."USLUGI" 
   (	"USLUGA_ID" NUMBER(19,0), 
	"CENA" NUMBER(19,0), 
	"NAZWA" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SZKOLAJAZDY.HIBERNATE_SEQUENCES
SET DEFINE OFF;
REM INSERTING into SZKOLAJAZDY.INSTRUKTORZY
SET DEFINE OFF;
Insert into SZKOLAJAZDY.INSTRUKTORZY (INSTRUKTOR_ID,CZY_ADMIN,DATA_DODANIA,EMAIL,GODZ_ROZPOCZECIA,GODZ_ZAKONCZENIA,HASLO,IMIE,NAZWISKO) values ('105','1',to_date('19/05/28','RR/MM/DD'),'b','b','b','b','b','b');
REM INSERTING into SZKOLAJAZDY.KATEGORIE
SET DEFINE OFF;
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('200','A');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('201','B');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('203','C');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('204','D');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('205','T');
REM INSERTING into SZKOLAJAZDY.KATEGORIE_INSTRUKTOROW
SET DEFINE OFF;
Insert into SZKOLAJAZDY.KATEGORIE_INSTRUKTOROW (ID_WPISU,INSTRUCTOR_ID,KATEGORIA_ID) values ('113','105','204');
Insert into SZKOLAJAZDY.KATEGORIE_INSTRUKTOROW (ID_WPISU,INSTRUCTOR_ID,KATEGORIA_ID) values ('112','105','200');
REM INSERTING into SZKOLAJAZDY.KURSANCI
SET DEFINE OFF;
Insert into SZKOLAJAZDY.KURSANCI (KURSANT_ID,DATA_REJESTRACJI,EMAIL,HASLO,IMIE,NAZWISKO,PESEL,PKK) values ('118',to_date('19/05/29','RR/MM/DD'),'f','f','f','ff','f','f');
Insert into SZKOLAJAZDY.KURSANCI (KURSANT_ID,DATA_REJESTRACJI,EMAIL,HASLO,IMIE,NAZWISKO,PESEL,PKK) values ('104',to_date('19/05/28','RR/MM/DD'),'a','a','a','a','a','a');
REM INSERTING into SZKOLAJAZDY.PLATNOSCI
SET DEFINE OFF;
REM INSERTING into SZKOLAJAZDY.REZERWACJE
SET DEFINE OFF;
Insert into SZKOLAJAZDY.REZERWACJE (REZERWACJA_ID,DATA_DODANIA,DATA_REZERWACJI,GODZ_ROZPOCZECIA,INSTRUKTOR_ID,KATEGORIA_ID,KURSANT_ID,USLUGA_ID) values ('117',to_date('19/05/28','RR/MM/DD'),to_date('19/01/01','RR/MM/DD'),'6','105','204','104','119');
Insert into SZKOLAJAZDY.REZERWACJE (REZERWACJA_ID,DATA_DODANIA,DATA_REZERWACJI,GODZ_ROZPOCZECIA,INSTRUKTOR_ID,KATEGORIA_ID,KURSANT_ID,USLUGA_ID) values ('114',to_date('19/05/28','RR/MM/DD'),to_date('19/05/01','RR/MM/DD'),'6','105','200','118','119');
REM INSERTING into SZKOLAJAZDY.USLUGI
SET DEFINE OFF;
Insert into SZKOLAJAZDY.USLUGI (USLUGA_ID,CENA,NAZWA) values ('105','100','test');
Insert into SZKOLAJAZDY.USLUGI (USLUGA_ID,CENA,NAZWA) values ('119','300','test2');
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SZKOLAJAZDY"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;



/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SZKOLAJAZDY"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'JDJZJY66PR1TL9O0A9M0A99FCQKC4S';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;



/
--------------------------------------------------------
--  Constraints for Table INSTRUKTORZY
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" ADD PRIMARY KEY ("INSTRUKTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("HASLO" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("GODZ_ROZPOCZECIA" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("CZY_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("INSTRUKTOR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURSANCI
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" ADD PRIMARY KEY ("KURSANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("HASLO" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("KURSANT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HIBERNATE_SEQUENCES
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."HIBERNATE_SEQUENCES" ADD PRIMARY KEY ("SEQUENCE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."HIBERNATE_SEQUENCES" MODIFY ("SEQUENCE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD PRIMARY KEY ("REZERWACJA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("USLUGA_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("KURSANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("KATEGORIA_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("INSTRUKTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("GODZ_ROZPOCZECIA" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("DATA_REZERWACJI" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("DATA_DODANIA" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("REZERWACJA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USLUGI
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."USLUGI" ADD PRIMARY KEY ("USLUGA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."USLUGI" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."USLUGI" MODIFY ("USLUGA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KATEGORIE
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE" ADD PRIMARY KEY ("KATEGORIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE" MODIFY ("KATEGORIA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KATEGORIE_INSTRUKTOROW
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" ADD PRIMARY KEY ("ID_WPISU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" MODIFY ("KATEGORIA_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" MODIFY ("INSTRUCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" MODIFY ("ID_WPISU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."PLATNOSCI" ADD PRIMARY KEY ("PLATNOSC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."PLATNOSCI" MODIFY ("KURSANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."PLATNOSCI" MODIFY ("PLATNOSC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table KATEGORIE_INSTRUKTOROW
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" ADD CONSTRAINT "FK16HBUB66L7KCEF21U0HVV2HQG" FOREIGN KEY ("KATEGORIA_ID")
	  REFERENCES "SZKOLAJAZDY"."KATEGORIE" ("KATEGORIA_ID") ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" ADD CONSTRAINT "FKBVLPEQ23L57625L7SWC28I53R" FOREIGN KEY ("INSTRUCTOR_ID")
	  REFERENCES "SZKOLAJAZDY"."INSTRUKTORZY" ("INSTRUKTOR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."PLATNOSCI" ADD CONSTRAINT "FKJEY9S8XLNA73E48WF0XGWVQEJ" FOREIGN KEY ("KURSANT_ID")
	  REFERENCES "SZKOLAJAZDY"."KURSANCI" ("KURSANT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD CONSTRAINT "FKC66GNDOB7Q4ULAFSTG3DVPMMV" FOREIGN KEY ("KURSANT_ID")
	  REFERENCES "SZKOLAJAZDY"."KURSANCI" ("KURSANT_ID") ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD CONSTRAINT "FKOXVQVD63LTWGME9ATWSWQHPYL" FOREIGN KEY ("INSTRUKTOR_ID")
	  REFERENCES "SZKOLAJAZDY"."INSTRUKTORZY" ("INSTRUKTOR_ID") ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD CONSTRAINT "FKRYEYNHQDKR12SSY8B900D3C2M" FOREIGN KEY ("USLUGA_ID")
	  REFERENCES "SZKOLAJAZDY"."USLUGI" ("USLUGA_ID") ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD CONSTRAINT "FKTBR9HH4YX78J7O7YLXPQJC9KJ" FOREIGN KEY ("KATEGORIA_ID")
	  REFERENCES "SZKOLAJAZDY"."KATEGORIE" ("KATEGORIA_ID") ENABLE;
