--------------------------------------------------------
--  File created - poniedziałek-maja-27-2019   
--------------------------------------------------------
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_CUST_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_ORDER_ITEMS_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_ORD_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_PROD_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."DEMO_USERS_SEQ";
DROP SEQUENCE "SZKOLAJAZDY"."HIBERNATE_SEQUENCE";
DROP TABLE "SZKOLAJAZDY"."HIBERNATE_SEQUENCES" cascade constraints;
DROP TABLE "SZKOLAJAZDY"."INSTRUKTORZY" cascade constraints;
DROP TABLE "SZKOLAJAZDY"."KATEGORIE" cascade constraints;
DROP TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" cascade constraints;
DROP TABLE "SZKOLAJAZDY"."KURSANCI" cascade constraints;
DROP TABLE "SZKOLAJAZDY"."PLATNOSCI" cascade constraints;
DROP TABLE "SZKOLAJAZDY"."REZERWACJE" cascade constraints;
DROP TABLE "SZKOLAJAZDY"."USLUGI" cascade constraints;
DROP FUNCTION "SZKOLAJAZDY"."CUSTOM_AUTH";
DROP FUNCTION "SZKOLAJAZDY"."CUSTOM_HASH";
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "SZKOLAJAZDY"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table HIBERNATE_SEQUENCES
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."HIBERNATE_SEQUENCES" 
   (	"SEQUENCE_NAME" VARCHAR2(255 CHAR), 
	"NEXT_VAL" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSTRUKTORZY
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."INSTRUKTORZY" 
   (	"INSTRUKTOR_ID" NUMBER(*,0), 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"GODZ_ROZPOCZECIA" VARCHAR2(20 BYTE), 
	"GODZ_ZAKONCZENIA" VARCHAR2(20 BYTE), 
	"DATA_DODANIA" DATE, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"HASLO" VARCHAR2(20 BYTE), 
	"CZY_ADMIN" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KATEGORIE
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."KATEGORIE" 
   (	"KATEGORIA_ID" NUMBER(*,0), 
	"SYMBOL" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KATEGORIE_INSTRUKTOROW
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" 
   (	"KATEGORIA_ID" NUMBER(*,0), 
	"INSTRUCTOR_ID" NUMBER(*,0), 
	"ID_WPISU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KURSANCI
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."KURSANCI" 
   (	"KURSANT_ID" NUMBER(*,0), 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"PESEL" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PKK" VARCHAR2(20 BYTE), 
	"HASLO" VARCHAR2(20 BYTE), 
	"DATA_REJESTRACJI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLATNOSCI
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."PLATNOSCI" 
   (	"PLATNOSC_ID" NUMBER, 
	"KURSANT_ID" NUMBER, 
	"KWOTA" NUMBER, 
	"DATA_PLATNOSCI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."REZERWACJE" 
   (	"REZERWACJA_ID" NUMBER(*,0), 
	"USLUGA_ID" NUMBER, 
	"KURSANT_ID" NUMBER, 
	"INSTRUKTOR_ID" NUMBER, 
	"DATA_DODANIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USLUGI
--------------------------------------------------------

  CREATE TABLE "SZKOLAJAZDY"."USLUGI" 
   (	"USLUGA_ID" NUMBER, 
	"NAZWA" VARCHAR2(20 BYTE), 
	"CENA" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SZKOLAJAZDY.HIBERNATE_SEQUENCES
SET DEFINE OFF;
Insert into SZKOLAJAZDY.HIBERNATE_SEQUENCES (SEQUENCE_NAME,NEXT_VAL) values ('default','16');
REM INSERTING into SZKOLAJAZDY.INSTRUKTORZY
SET DEFINE OFF;
Insert into SZKOLAJAZDY.INSTRUKTORZY (INSTRUKTOR_ID,IMIE,NAZWISKO,GODZ_ROZPOCZECIA,GODZ_ZAKONCZENIA,DATA_DODANIA,EMAIL,HASLO,CZY_ADMIN) values ('30','ins','ins','8:00','10:00',to_date('19/05/26','RR/MM/DD'),'ins','ins','0');
Insert into SZKOLAJAZDY.INSTRUKTORZY (INSTRUKTOR_ID,IMIE,NAZWISKO,GODZ_ROZPOCZECIA,GODZ_ZAKONCZENIA,DATA_DODANIA,EMAIL,HASLO,CZY_ADMIN) values ('0','Mateusz','Sliwkas','10:00','18:00',to_date('19/05/22','RR/MM/DD'),'mateosl@wp.pl','test123','1');
Insert into SZKOLAJAZDY.INSTRUKTORZY (INSTRUKTOR_ID,IMIE,NAZWISKO,GODZ_ROZPOCZECIA,GODZ_ZAKONCZENIA,DATA_DODANIA,EMAIL,HASLO,CZY_ADMIN) values ('46','instr','ukgtor','fd','df',to_date('19/05/26','RR/MM/DD'),'tester@ad.pl','fd','0');
REM INSERTING into SZKOLAJAZDY.KATEGORIE
SET DEFINE OFF;
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('0','A');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('1','B');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('2','A1');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('3','A2');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('4','D');
Insert into SZKOLAJAZDY.KATEGORIE (KATEGORIA_ID,SYMBOL) values ('5','C');
REM INSERTING into SZKOLAJAZDY.KATEGORIE_INSTRUKTOROW
SET DEFINE OFF;
REM INSERTING into SZKOLAJAZDY.KURSANCI
SET DEFINE OFF;
Insert into SZKOLAJAZDY.KURSANCI (KURSANT_ID,IMIE,NAZWISKO,PESEL,EMAIL,PKK,HASLO,DATA_REJESTRACJI) values ('60','adsads','ads','das','ads','as','asd',to_date('19/05/27','RR/MM/DD'));
Insert into SZKOLAJAZDY.KURSANCI (KURSANT_ID,IMIE,NAZWISKO,PESEL,EMAIL,PKK,HASLO,DATA_REJESTRACJI) values ('0','Emilia','Augustyn','9999999','test@user.pl','1211221','haslo',to_date('19/05/06','RR/MM/DD'));
REM INSERTING into SZKOLAJAZDY.PLATNOSCI
SET DEFINE OFF;
Insert into SZKOLAJAZDY.PLATNOSCI (PLATNOSC_ID,KURSANT_ID,KWOTA,DATA_PLATNOSCI) values ('81','60','100',to_date('19/05/27','RR/MM/DD'));
Insert into SZKOLAJAZDY.PLATNOSCI (PLATNOSC_ID,KURSANT_ID,KWOTA,DATA_PLATNOSCI) values ('61','0','100',to_date('19/05/27','RR/MM/DD'));
REM INSERTING into SZKOLAJAZDY.REZERWACJE
SET DEFINE OFF;
Insert into SZKOLAJAZDY.REZERWACJE (REZERWACJA_ID,USLUGA_ID,KURSANT_ID,INSTRUKTOR_ID,DATA_DODANIA) values ('82','53','60','30',to_date('19/05/27','RR/MM/DD'));
Insert into SZKOLAJAZDY.REZERWACJE (REZERWACJA_ID,USLUGA_ID,KURSANT_ID,INSTRUKTOR_ID,DATA_DODANIA) values ('59','53','0','0',to_date('19/05/27','RR/MM/DD'));
REM INSERTING into SZKOLAJAZDY.USLUGI
SET DEFINE OFF;
Insert into SZKOLAJAZDY.USLUGI (USLUGA_ID,NAZWA,CENA) values ('53','Jazda dodatkowa','50');
--------------------------------------------------------
--  DDL for Index KURSANCI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZKOLAJAZDY"."KURSANCI_PK" ON "SZKOLAJAZDY"."KURSANCI" ("KURSANT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KATEGORIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZKOLAJAZDY"."KATEGORIE_PK" ON "SZKOLAJAZDY"."KATEGORIE" ("KATEGORIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USLUGI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZKOLAJAZDY"."USLUGI_PK" ON "SZKOLAJAZDY"."USLUGI" ("USLUGA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INSTRUKTORZY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZKOLAJAZDY"."INSTRUKTORZY_PK" ON "SZKOLAJAZDY"."INSTRUKTORZY" ("INSTRUKTOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REZERWACJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZKOLAJAZDY"."REZERWACJE_PK" ON "SZKOLAJAZDY"."REZERWACJE" ("REZERWACJA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KATEGORIE_INSTRUKTOROW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW_PK" ON "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" ("ID_WPISU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SZKOLAJAZDY"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;



/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SZKOLAJAZDY"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'JDJZJY66PR1TL9O0A9M0A99FCQKC4S';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;



/
--------------------------------------------------------
--  Constraints for Table HIBERNATE_SEQUENCES
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."HIBERNATE_SEQUENCES" MODIFY ("SEQUENCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."HIBERNATE_SEQUENCES" ADD PRIMARY KEY ("SEQUENCE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USLUGI
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."USLUGI" ADD CONSTRAINT "USLUGI_PK" PRIMARY KEY ("USLUGA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."USLUGI" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."USLUGI" MODIFY ("USLUGA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSTRUKTORZY
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" ADD CONSTRAINT "INSTRUKTORZY_PK" PRIMARY KEY ("INSTRUKTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("GODZ_ROZPOCZECIA" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("INSTRUKTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("HASLO" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."INSTRUKTORZY" MODIFY ("CZY_ADMIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."PLATNOSCI" MODIFY ("KURSANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."PLATNOSCI" MODIFY ("PLATNOSC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_PK" PRIMARY KEY ("REZERWACJA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("INSTRUKTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("KURSANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("USLUGA_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" MODIFY ("REZERWACJA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KATEGORIE_INSTRUKTOROW
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" ADD CONSTRAINT "KATEGORIE_INSTRUKTOROW_PK" PRIMARY KEY ("ID_WPISU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" MODIFY ("ID_WPISU" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" MODIFY ("INSTRUCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" MODIFY ("KATEGORIA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURSANCI
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" ADD CONSTRAINT "KURSANCI_PK" PRIMARY KEY ("KURSANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("HASLO" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SZKOLAJAZDY"."KURSANCI" MODIFY ("KURSANT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KATEGORIE
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE" ADD CONSTRAINT "KATEGORIE_PK" PRIMARY KEY ("KATEGORIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE" MODIFY ("KATEGORIA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table KATEGORIE_INSTRUKTOROW
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" ADD CONSTRAINT "KATEGORIE_INSTRUKTOROW_FK1" FOREIGN KEY ("KATEGORIA_ID")
	  REFERENCES "SZKOLAJAZDY"."KATEGORIE" ("KATEGORIA_ID") ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."KATEGORIE_INSTRUKTOROW" ADD CONSTRAINT "KATEGORIE_INSTRUKTOROW_FK2" FOREIGN KEY ("KATEGORIA_ID")
	  REFERENCES "SZKOLAJAZDY"."INSTRUKTORZY" ("INSTRUKTOR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."PLATNOSCI" ADD CONSTRAINT "PLATNOSCI_FK1" FOREIGN KEY ("KURSANT_ID")
	  REFERENCES "SZKOLAJAZDY"."KURSANCI" ("KURSANT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_FK1" FOREIGN KEY ("USLUGA_ID")
	  REFERENCES "SZKOLAJAZDY"."USLUGI" ("USLUGA_ID") ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_FK2" FOREIGN KEY ("KURSANT_ID")
	  REFERENCES "SZKOLAJAZDY"."KURSANCI" ("KURSANT_ID") ENABLE;
  ALTER TABLE "SZKOLAJAZDY"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_FK3" FOREIGN KEY ("INSTRUKTOR_ID")
	  REFERENCES "SZKOLAJAZDY"."INSTRUKTORZY" ("INSTRUKTOR_ID") ENABLE;
